### PR TITLE
Add dataset links and semantic changes

### PR DESCRIPTION
**Pull request by KaiWaldrant**
## Describe your changes

* Added url to the benchmark datasets that link to the dataset page
* Add "n cells x m genes" to datasetinfo instead of "n x m"
* Fix used in links on the datasets details pages

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [x] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [x] CI Preview succeeds and looks good!

### CODE REVIEW

**Comment by KaiWaldrant** [comment]
Noticed an issue with datasets in `spatial decomposition`. It lists `DESTVI` but is not submitted to the datasets pages because this is a simulated dataset. https://feature-no-ref-add-dataset-return-link--openproblems.netlify.app/results/spatial_decomposition/#dataset-info

**Comment by rcannood** [comment]
I also notice that for this dataset

https://feature-no-ref-add-dataset-return-link--openproblems.netlify.app/datasets/tenx_visium/post_xenium/human_colon_cancer/

The "Used in" link isn't working. I can imagine why this is, but could you take a look?

**Comment by rcannood** [comment]
> Noticed an issue with datasets in `spatial decomposition`. It lists `DESTVI` but is not submitted to the datasets pages because this is a simulated dataset. https://feature-no-ref-add-dataset-return-link--openproblems.netlify.app/results/spatial_decomposition/#dataset-info

Is it possible to only add a link if that dataset exists?

**Review by rcannood — CHANGES_REQUESTED** [review]
See other comments ^^

**Review by rcannood — APPROVED** [review]
LGTM!

**Pull request merged**
