### PR TITLE
rework benchmark results

### PR DESCRIPTION
**Pull request by rcannood**
This PR explores a different implementation for rendering the benchmarking results.

[Preview](https://deploy-preview-90--openproblems-sca.netlify.app/benchmarks/)

### CODE REVIEW

**Comment by rcannood** [comment]
I'm going to let GitHub Actions generate a preview

**Comment by rcannood** [comment]
@dburkhardt Are there any execution logs for the build of this branch on Netlify?

**Comment by scottgigante** [comment]
Looks like it hasn't deployed, maybe because the target was not main. I'm closing and reopening to trigger the preview

**Comment by scottgigante** [comment]
Can we split the wowchemy upgrade from the format change so I can see just the diff that I care about or is that too much work?

**Comment by scottgigante-immunai** [comment]
From @LuckyMD:
> This looks really good. I would still keep the interactive per-dataset tables that can be ordered though (with the paper, code, etc links). Also, I would probably avoid the method description in favour of the links.

I agree - the existing tables should be kept, and the method list should be removed. Dataset list should probably be merged with the former table that had links to the per-dataset tables.

Also:
* I don't think baselines should be so front-and-centre on the results page -- they should be mostly not visible to the user. I'd remove them from the funkyheatmap and not have a list of baselines.
* Are the funkyheatmap scores the baseline-scaled scores (rounded to [0,1])? or are you scaling to (min, max)?
* The funkyheatmap cuts off metric labels on the right hand side of the plot (e.g. spatial decomposition)
* The funkyheatmap legend gets cut off on the right (e.g. regulatory effect prediction)
* The funkyheatmap column labels overlap with each other when the columns are too narrow (e.g. regulatory effect prediction)
* The funkyheatmap should probably have a dark mode, it sticks out pretty badly against the dark mode background

**Comment by rcannood** [comment]
> Can we split the wowchemy upgrade from the format change so I can see just the diff that I care about or is that too much work?

Good news! The wowchemy already is in a different branch! You can compare between the two.

**Comment by scottgigante-immunai** [comment]
Oof. Diff is still 279 files. https://github.com/openproblems-bio/website/compare/update_wowchemy...update_wowchemy_and_benchmarks

**Comment by rcannood** [comment]
> Oof. Diff is still 279 files. [update_wowchemy...update_wowchemy_and_benchmarks](https://github.com/openproblems-bio/website/compare/update_wowchemy...update_wowchemy_and_benchmarks)

Oof, okay, that's still quite a lot.

In that case, how about this. With the new format, the only updates that are needed are the json files in the data folder inside of each task (as long as we're updating the results and not the benchmark). Does that help?

**Comment by scottgigante** [comment]
That's helpful, thanks!

**Comment by rcannood** [comment]
* Summary should be <h4>

**Comment by dburkhardt** [comment]
High level - this is great progress and I think we're closer to having a good results summary homepage.

In general, we want these homepages to be more streamlined and with less content. There's a lot of information, and it doesn't guide a user to the information they're looking for. From an asthetic perspective, the benchmarks should model the paperswithcode SOTA ([example](https://paperswithcode.com/task/medical-image-segmentation). 


Here's how I would lay them out:
* Add benchmark image at the top of the homepage or in little image container on the right.
* Add header; "Description"
* Rename "Results" above the funky heatmap to "Summarized results"
* Right now, the "Methods" "Metrics" "Datasets" headers are just too long with too much information. I'm not sure the best way to layer information here. What do we expect most people to navigate to? Per data-set benchmark pages? Then move that first and remove the rest of the bullets. Another option is to have a sidebar here with links to pages with information for each of these sections. Happy to brainstorm solutions.

> I don't think baselines should be so front-and-centre on the results page -- they should be mostly not visible to the user. I'd remove them from the funkyheatmap and not have a list of baselines.

I'm on the fence about this, but not opposed to removing them

> The funkyheatmap should probably have a dark mode, it sticks out pretty badly against the dark mode background

Can you just export the images with a transparent background?

**Comment by rcannood** [comment]
## Showing baselines

> @scottgigante: I don't think baselines should be so front-and-centre on the results page -- they should be mostly not visible to the user. I'd remove them from the funkyheatmap and not have a list of baselines.

> @dburkhardt: I'm on the fence about this, but not opposed to removing them

I think there is a lot of value in showing the baselines, or at least being able to show them, as it can provide confidence in the results that we're getting. Being able to toggle whether results are shown would be very useful, though.

## Too much information

> @LuckyMD: This looks really good. I would still keep the interactive per-dataset tables that can be ordered though (with the paper, code, etc links). Also, I would probably avoid the method description in favour of the links.

> @scottgigante: I agree - the existing tables should be kept, and the method list should be removed. Dataset list should probably be merged with the former table that had links to the per-dataset tables.

> @dburkhardt In general, we want these homepages to be more streamlined and with less content. There's a lot of information, and it doesn't guide a user to the information they're looking for. From an asthetic perspective, the benchmarks should model the paperswithcode SOTA ([example](https://paperswithcode.com/task/medical-image-segmentation)). 
> Here's how I would lay them out:
>     Add benchmark image at the top of the homepage or in little image container on the right.
>     Add header; "Description"
>     Rename "Results" above the funky heatmap to "Summarized results"
>     Right now, the "Methods" "Metrics" "Datasets" headers are just too long with too much information. I'm not sure the best way to layer information here. What do we expect most people to navigate to? Per data-set benchmark pages? Then move that first and remove the rest of the bullets. Another option is to have a sidebar here with links to pages with information for each of these sections. Happy to brainstorm solutions.

Ok, I'll look into reworking the layout :+1:

## Other remarks

> @scottgigante: Are the funkyheatmap scores the baseline-scaled scores (rounded to [0,1])? or are you scaling to (min, max)?

The scores are scaled to (min, max). If the scaled scores were always between [0, 1], I could use the unmodified scores.

> @scottgigante :
>     The funkyheatmap cuts off metric labels on the right hand side of the plot (e.g. spatial decomposition)
>     The funkyheatmap legend gets cut off on the right (e.g. regulatory effect prediction)
>     The funkyheatmap column labels overlap with each other when the columns are too narrow (e.g. regulatory effect prediction)
>     The funkyheatmap should probably have a dark mode, it sticks out pretty badly against the dark mode background

I'll look into it!

**Comment by scottgigante-immunai** [comment]
Thanks @rcannood !!

> I think there is a lot of value in showing the baselines, or at least being able to show them, as it can provide confidence in the results that we're getting.

Agreed. I think I'd default to not showing them, with an option to show them.

> The scores are scaled to (min, max). If the scaled scores were always between [0, 1], I could use the unmodified scores.

I think it would be better to clip the min to zero -- there are many metrics where a method can perform arbitrarily badly. And when baselines are excluded, if the max if less than 1, we should leave it less than 1. If max is >1 I agree that this is a bug in the baselines (many of which are being addressed in the next run) and we should rescale for now.

**Comment by rcannood** [comment]
Time for an update! ([example](https://deploy-preview-90--openproblems-sca.netlify.app/benchmarks/label_projection/))

* Data table: The data table has been added back. For now it only shows the scaled scores (no slider, will add that back later). The data table actually contains all of the results, but a button for filtering the rows has been added. The default dataset filtering is set to the overall mean.
* Funkyheatmap:
  - Baseline methods have been removed.
  - Funkyheatmap doesn't rescale the scaled score, but does clip the scores to [0, 1]
* Removed some of the clutter. Everything I removed I stored as Details at the end of the page. Eventually they'll be moved to the developers documentation.

Known issues:
* No support for dark mode. Exporting the PNG without background made the issue even worse.
* Labels and legends are still being cut off when there is not enough data
* The info json files are missing a lot of descriptions

@scottgigante-immunai How much needs to be done before we can merge this PR? From a technical perspective, I'd say the PR can be merged as it's already an improvement over the current state.

**Comment by scottgigante-immunai** [comment]
Thanks @rcannood ! Some additional requests before I agree that this is better than what we have now:

* dark mode is unreadable. Need to at least add the white background back into the png and fix the text colour in the table
* the filter rows version of viewing individual dataset results is quite confusing. I'd be in favour of either returning to separate pages for each results table as we had before, or a more explicit display that shows the names of the datasets without having to click into another screen
* the references being hyperlinks in the filter rows screen is confusing -- I wanted to filter the table and instead I got taken to the bibliography. Maybe just hyperlink a paper icon to the right of the name? And definitely should be a `target="_blank"`.
* Metric descriptions should appear below the task description as before -- only method and dataset descriptions should be moved down.
* Text associated with metric reference is ugly (e.g. Cell Cycle Score: Missing ‘metric_description’. [[luecken2022benchmarking]](https://deploy-preview-90--openproblems-sca.netlify.app/bibliography#luecken2022benchmarking)). Can this either be a paper icon or a rendered citation?

**Comment by rcannood** [comment]
Thanks for taking the time to look at this and give feedback!

> dark mode is unreadable. Need to at least add the white background back into the png and fix the text colour in the table

Fixed! I set the background of the png to white and added css to make sure the datatable is rendered properly. 

> the filter rows version of viewing individual dataset results is quite confusing

The benefits of being able to set the filters like this is that it allows someone to:

* View average scores
* View scores for just one method
* View scores for just one dataset
* View all results but sort by dataset

> the references being hyperlinks in the filter rows screen is confusing

Fixed! References are now only shown in the details.

> Metric descriptions should appear below the task description as before -- only method and dataset descriptions should be moved down.

Check!

> Text associated with metric reference is ugly (e.g. Cell Cycle Score: Missing ‘metric_description’. [[luecken2022benchmarking]](https://deploy-preview-90--openproblems-sca.netlify.app/bibliography#luecken2022benchmarking)). Can this either be a paper icon or a rendered citation?

I changed it to "**Name of method**<sup>[2](http://localhost:1313/bibliography#cover1967nearest)</sup>".

**Comment by rcannood** [comment]
@scottgigante-immunai Do you have any more ideas on what could be improved?

Also, would you be able to look into updating the jsons? The [script I used to generate the data files](https://github.com/openproblems-bio/website/blob/update_wowchemy_and_benchmarks/content/benchmarks/_generate_metadata.py) uses the `.raw.json` files and the `openproblems` package and was partially based on the scripts that are in the openproblems repo.

**Comment by scottgigante-immunai** [comment]
Thanks! This is already much better.

Re: the filtered table, I agree this is nice -- I just wonder if we can make datasets more prominent. You can see all the methods in the table in the default view (since they are visible rows) but the fact that there are even datasets in the filters is not obvious. Perhaps something like this with checkboxes (excuse my abuse of notation)

```
## Scaled scores
<right align>[[CSV]] | [[Excel]]</>
Datasets: [X] Overall mean [ ] Pancreas (batch) [ ] Immune (batch)
[[Advanced filters]]

<table/>
```

A couple more nitpicks on layout and I'd also like to hear @LuckyMD 's thoughts.

* I strongly prefer metrics where they were before: Task description, metrics, then results.
* References have gone from being quite prominent (a column in the per-dataset results table or a link in the main datasets table) to being hidden in the supplement. Maybe you can put similar superscript refs in the results table for methods and datasets?

**Comment by scottgigante-immunai** [comment]
Re: json, I'm working on it in https://github.com/openproblems-bio/openproblems/pull/810

**Comment by rcannood** [comment]
> Perhaps something like this with checkboxes (excuse my abuse of notation)

I agree it's a good diea, but is it okay if I turn this into a separate issue which I could take a look at in the future?

> I strongly prefer metrics where they were before: Task description, metrics, then results.

Done!

> References have gone from being quite prominent (a column in the per-dataset results table or a link in the main datasets table) to being hidden in the supplement. Maybe you can put similar superscript refs in the results table for methods and datasets?

Done!

**Comment by scottgigante-immunai** [comment]
Thanks! Looks great.

> is it okay if I turn this into a separate issue which I could take a look at in the future?

Reasonable request. Maybe an interim solution is to rename "Filters" to "Filter datasets / methods"?

**Comment by rcannood** [comment]
Good idea! Done!

**Comment by scottgigante-immunai** [comment]
Thanks @rcannood ! This is now just pending completion of https://github.com/openproblems-bio/openproblems/pull/810 (which itself is blocked by task leaders writing method descriptions.)

**Comment by scottgigante-immunai** [comment]
One more issue with the heatmap (not urgent) -- `kBET` is incorrectly rendered as `Kbet`

**Comment by scottgigante-immunai** [comment]
Another, more urgent issue -- the ranking in the heatmap and the ranking in the table don't match. See e.g. https://deploy-preview-121--openproblems-sca.netlify.app/benchmarks/batch_integration_feature/

**Comment by scottgigante-immunai** [comment]
Another issue: baseline results are missing in `Visualization of raw results` (the place where they are most useful)

**Pull request closed without merging**
