### PR TITLE
experiment with new layout and new tasks pages

### PR DESCRIPTION
**Pull request by dsm-72**
This creates the new sitemap. Rather than changing the existing stuff, a new dir was created (content/tasks) and all of this is listed there. This allows for us to have it "hidden" for the time being while it is developed. Mostly doing this so it gets run on netlify. 

Naturally md should be autogenerated.

### CODE REVIEW

**Comment by dsm-72** [comment]
@scottgigante  the preview link? https://deploy-preview-13--openproblems-sca.netlify.app/tasks/

**Comment by dburkhardt** [comment]
image
@scottgigante  it's part of the CI/CD

**Comment by scottgigante** [comment]
Oh great, thanks. Didn't realise that link took me to the page itself.

**Comment by scottgigante-immunai** [comment]
@dsm-72 all TODOs have been fixed on main. Once you fix merge conflicts this should be ready to merge.

**Comment by scottgigante-immunai** [comment]
@dburkhardt @dsm-72 I fixed all the merge conflicts except one which I'm not qualified to comment on. `layouts/partials/navbar.html` was removed in 08bb865b4643d5c982c2a5603ee2b536fad865d3. I'll let you two figure that out then this should be good to merge

**Comment by scottgigante-immunai** [comment]
Thanks for all your hard work @dsm-72 !

**Pull request merged**
