### PR TITLE
update license

### PR DESCRIPTION
**Pull request by KaiWaldrant**
## Describe your changes
Update license to Creative Commons CC-BY

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [ ] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [x] CI Preview succeeds and looks good!

### CODE REVIEW

**Comment by LuckyMD** [comment]
Conceptually this looks good, I can't see a preview of the deployment anywhere atm, but I trust this is what I was hoping for. Thanks a lot, @scottgigante-immunai !

**Review by LuckyMD — APPROVED** [review]

**Comment by scottgigante-immunai** [comment]
@LuckyMD preview should be visible at https://update-cc-by--openproblems.netlify.app/ in the footer of the page.

**Comment by rcannood** [comment]
I force pushed a commit to add Scott as a co-author to the proposed changes :)

I'm wondering whether we it would make more sense to use dual licensing (MIT for source code, CC-BY for documentation and results), but maybe this makes things unnecessarily complicated.

**Comment by scottgigante-immunai** [comment]
I thought about it, but I think that overcomplicates things. Most of the code that we would care about being MIT licensed is not in this repo

**Comment by KaiWaldrant** [comment]
If the checks are ok this can be merged ? @scottgigante-immunai @rcannood

**Review by rcannood — APPROVED** [review]

**Pull request merged**
