### PR TITLE
add stats to tasks

### PR DESCRIPTION
**Pull request by rcannood**
## Describe your changes

* Adds benchmark task statistics to the [Results page](https://feature-no-ref-add-task-stats--openproblems.netlify.app/results/)

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [x] CI Preview succeeds and looks good!

### CODE REVIEW

**Comment by KaiWaldrant** [comment]
Looks like the card css is also applied to the summary table options. not really a fan.
image

**Review by KaiWaldrant — CHANGES_REQUESTED** [review]
Looks good apart from the comment above.

**Comment by rcannood** [comment]
Thanks for pointing this out -- should be fixed now!

**Review by KaiWaldrant — APPROVED** [review]
LGTM!

**Pull request merged**
