### PR TITLE
Beautify benchmarking tables

### LINKED ISSUE #30: Website beautification
Some notes from my side:
* metric names are too close together in the results table (also Paper Code and Year too close)
* Ordering results by rank would be good
* would be good to have a link to go back from dataset results to task
* we need task headings also where the task is explained: when you click on “label projection”, the next page should be titled “label projection”
* mentioned already several times, but thumbnails are not there atm

### PR DESCRIPTION
**Pull request by dsm-72**
This PR:

* increases padding
* ~adds gray 1px borders~
* left aligns `Name` and center aligns `Paper`

Closes #30

### CODE REVIEW

**Comment by dsm-72** [comment]
Should be easy to manually merge @rcannood

**Comment by scottgigante-immunai** [comment]
Can you please name the PR something descriptive and use the comment to describe what was done? Hard for me to review without more details.

**Comment by rcannood** [comment]
Could you also resolve the conflicts with the main branch? :bow: thanks!

**Review by rcannood — CHANGES_REQUESTED** [review]
As mentioned by Scott, please provide a description of the proposed changes. Which proposed changes are you fixing?

Could you also resolve the conflicts with the main branch so it can be merged?

**Comment by dsm-72** [comment]
@scottgigante @rcannood see https://github.com/openproblems-bio/website/issues/30#issuecomment-1379308061

**Comment by scottgigante** [comment]
It's unclear to me what parts of that comment apply to this PR. Can you please just write in bullet points what this PR does?

**Comment by dsm-72** [comment]
@scottgigante that is a bullet point list. 

Anyway
- increase padding (done)
- add gray 1px borders (done)
- name needs to left align, paper center aligned)

the rest of the list are things which were never an issue or have already be resolved elsewhere

**Comment by scottgigante-immunai** [comment]
Thanks. I've updated the PR title and first comment body as an example for future PRs.

**Comment by scottgigante-immunai** [comment]
@mxposed I think the grey border looks bad.

With:
image

Without:
image

**Comment by mxposed** [comment]
@scottgigante-immunai I agree

**Comment by scottgigante-immunai** [comment]
@dsm-72 do you mind removing the border? Thanks

**Review by dsm-72 — COMMENTED** [review]
no more border

**Review by scottgigante-immunai — APPROVED** [review]
Thanks @dsm-72 ! @rcannood can you please re-review to unblock?

**Review by rcannood — APPROVED** [review]
LGTM! :)

**Pull request merged**
