### PR TITLE
Make funkyheatmap header text white

### LINKED ISSUE #171: Funky heatmap labels are less readable
Adding the dark mode #153 made the funky heatmap labels less readable. Can we fix this before releasing the dark mode?

Now:
Screenshot from 2023-03-10 17-07-33

Previously:
Screenshot from 2023-03-10 17-07-38

### PR DESCRIPTION
**Pull request by scottgigante-immunai**
## Issue ticket number and link
Closes #171

## Checklist before requesting a review
- [X] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [X] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md
(no, because it's fixing something that has not yet been released)

- [x] CI Preview succeeds and looks good!

### CODE REVIEW

**Comment by rcannood** [comment]
This seems to do the opposite of what we want -- Now the text is always black. Originally, the text was always white.

**Review by rcannood — CHANGES_REQUESTED** [review]
This seems to do the opposite of what we want -- Now the text is always black. Originally, the text was always white.

**Comment by mxposed** [comment]
Can we discuss how you want the funkyheatmap to look with the night theme? I can adapt different elements and use css variables for styles

**Review by rcannood — APPROVED** [review]

**Review by rcannood — CHANGES_REQUESTED** [review]
Header font is still black in non-dark mode. (clicked the wrong button before).

I'm strongly considering moving the dark mode out of the main branch and moving it into a separate branch, because it results in a lot of rendering artifacts (not just on this page). Once these are solved in properly, we can merge it back into main. @scottgigante-immunai wdyt?

**Comment by scottgigante** [comment]
Weird. I'll look into this tomorrow.

Re: other issues, what are they? Should be easy enough to fix.

**Review by rcannood — APPROVED** [review]

**Pull request merged**
