### PR TITLE
Add bibliography

### PR DESCRIPTION
**Pull request by scottgigante-immunai**
Draft for now

### CODE REVIEW

**Comment by scottgigante-immunai** [comment]
Okay, first attempt is up. Following IEEE reference guide (mostly). 

Example behaviour: https://deploy-preview-64--openproblems-sca.netlify.app/bibliography/#stuart2019comprehensive takes us direct to the citation
> Stuart, T., Butler, A., Hoffman, P., et al., "Comprehensive Integration of Single-Cell Data". Cell, vol. 177, no. 7, pp. 1888-1902.e21, 2019. [doi:10.1016/j.cell.2019.05.031.](http://dx.doi.org/10.1016/j.cell.2019.05.031)

Open to thoughts, input on style, etc.

**Comment by scottgigante-immunai** [comment]
What I would love to have if is you go to the page via an id, that entry is highlighted. Haven't figured out how to do that yet.

**Comment by scottgigante-immunai** [comment]
@dburkhardt @rcannood I've hit the end of my patience with hugo. If you have any tips on how to make [this](https://codepen.io/anon/pen/xfjrh) work on our site, I would be most grateful. In the meantime I think this is good enough to merge for now, unless you disagree.

**Comment by rcannood** [comment]
Thanks for your hard work ☺️ 

The code pen just send me to a lorum Ipsum. Is this expected?

**Comment by scottgigante-immunai** [comment]
Yep! The code pen demo shows an animated highlight and fade when you click on the "Jump to target" link.

Issue here is that when you click on a link like [https://openproblems.bio/bibliography#stuart2019comprehensive](https://deploy-preview-64--openproblems-sca.netlify.app/bibliography#stuart2019comprehensive) it takes you close to the citation of interest, but doesn't highlight it in any way.

**Comment by scottgigante-immunai** [comment]
@rcannood @dburkhardt any comments on this PR? Otherwise I think we should merge.

**Comment by scottgigante-immunai** [comment]
Ping @rcannood @dburkhardt :)

**Comment by LuckyMD** [comment]
So I do see a highlight on Stuart et al in [https://openproblems.bio/bibliography#stuart2019comprehensive](https://deploy-preview-64--openproblems-sca.netlify.app/bibliography#stuart2019comprehensive). Not when I click on the link, but when I then click on the url and load it again (not upon refresh, only when i press enter in the address bar.

Screenshot 2023-01-03 at 23 51 40

**Comment by scottgigante-immunai** [comment]
Oh interesting. I just tried different browsers and the highlight works as desired in firefox but not chrome or safari. I'll play around a bit more.

**Comment by scottgigante-immunai** [comment]
@dburkhardt I might need your help here. The CSS `:target` pseudo-element is triggering if you click a target link from the bibliography page, but not if you navigate directly to the target from the address bar or a link from another page. This issue is present in Chrome and Safari, but not Firefox. Investigations on other usages of `:target` indicate this _should_ work in Chrome -- see e.g. https://madmurphy.github.io/takefive.css/#quotation-example. I suspect Hugo/Wowchemy might be to blame. One possibility is to render the bibliography html in advance rather than building it with the bibtex formatter I'm using, but I'd rather not if we can avoid it.

**Comment by scottgigante-immunai** [comment]
Hey, I did it! @LuckyMD @dburkhardt @rcannood please take a look.

**Comment by LuckyMD** [comment]
Works for me on chrome and firefox now, whether i refresh the page, load it, or click on the link :). Well done, man! This is really cool!

**Review by LuckyMD — APPROVED** [review]
Did not review code, but the bibliography page looks good and highlighting works, so i'm happy!

**Comment by LuckyMD** [comment]
I did however just notice that the citations in the README and the results tables don't link to the citations page in the preview above, but instead they link to the papers themselves. Also, there are citations that are not linked yet (e.g., kBET in the README for batch integration).

**Comment by scottgigante-immunai** [comment]
> I did however just notice that the citations in the README and the results tables don't link to the citations page in the preview above, but instead they link to the papers themselves. Also, there are citations that are not linked yet (e.g., kBET in the README for batch integration).

Yep, this will be solved by https://github.com/openproblems-bio/openproblems/pull/720

**Pull request merged**
