### PR TITLE
Add CC-BY license

### PR DESCRIPTION
**Pull request by scottgigante-immunai**
## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Preview succeeds and looks good!

### CODE REVIEW

**Comment by scottgigante-immunai** [comment]
@rcannood deploy is broken. Any ideas?

**Comment by rcannood** [comment]
Probably because you don't have a netlify token installed in your fork

> Error: Timed out waiting for authorization. If you do not have a Netlify account, please create one at https://app.netlify.com/signup, then run netlify login again.

If you want the preview to work we either have to launch from the main repo or add the token to your account.

Can look into this in more detail when I'm back.

**Comment by scottgigante-immunai** [comment]
Lol @KaiWaldrant

**Comment by rcannood** [comment]
☺️

**Comment by scottgigante-immunai** [comment]
Closing in favour of #216

**Pull request closed without merging**
