### PR TITLE
Refactor/tables alternate

### PR DESCRIPTION
**Pull request by rcannood**
Alternate approach to #58.

This PR adds a button which filters columns based on whether their name ends with "Raw" or "Scaled". Column names are rendered without the ` *(Raw|Scaled)` suffix.

### CODE REVIEW

**Review by scottgigante-immunai — CHANGES_REQUESTED** [review]
Thanks @rcannood ! Some feedback:

* can you please make the "raw" and "scaled" text smaller by 2 points?
* can you make the slider 10 or 20% smaller and make it the same colour as the open problems logo?
* "Mean score" doesn't have a raw value (it is the mean of scaled scores). Should probably be left as is?

Otherwise, this looks great! Let me know when you're happy with the data format and I'll update the benchmark processing and send you the raw scores.

**Comment by rcannood** [comment]
If you don't add the raw/scales suffix to the mean score column, it will be left as is.

I'm happy with the data format! Feel free to update the data :)

I'll adapt the colours and sizes when I have the time tomorrow, but this PR could already be merged as soon as the raw values are filled in.

**Review by scottgigante-immunai — APPROVED** [review]

**Comment by scottgigante-immunai** [comment]
I think this is unquestionably better than what we currently have. I'm going to merge and we can discuss aesthetics etc in a new PR.

**Comment by scottgigante-immunai** [comment]
Thanks!

**Pull request merged**
