### PR TITLE
Add dataset pages

### PR DESCRIPTION
**Pull request by KaiWaldrant**
## Describe your changes

[Preview](https://add-datasets--openproblems.netlify.app/datasets/)

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [x] CI Preview succeeds and looks good!

### CODE REVIEW

**Comment by KaiWaldrant** [comment]
Need to wait for openproblems-bio/openproblems-v2/#325 is merged and run on the datasets to extract the updated metadata yamls. Does not work with current metadata yaml files.

**Review by rcannood — APPROVED** [review]
Looks good to me! What do you think @KaiWaldrant ?

**Comment by KaiWaldrant** [comment]
I noticed a horizontal scrollbar on the catogeries sidebar on the datasets overwiew page.

Everything else looks good to me.

**Comment by rcannood** [comment]
Hmmm.. do you think it's simple enough to center the "Datasets" label on the hero? At he moment it's a little to the left of where it needs to be

**Comment by rcannood** [comment]
Doh -- gt doesn't integrate automatically with the dark theme

**Comment by KaiWaldrant** [comment]
Looks like it is centered over the left side and does not include the space above the categories. seems like a bug to me. let me have a look.

**Comment by KaiWaldrant** [comment]
> Looks like it is centered over the left side and does not include the space above the categories. seems like a bug to me. let me have a look.

when adding the  categories to the page the hero gets the class of `column-page-left` like the content of the body but this should remain `column-page`. To me this seems like a bug. not sure how to bypass this.

**Comment by KaiWaldrant** [comment]
great hero image btw! :+1:

**Comment by KaiWaldrant** [comment]
> > Looks like it is centered over the left side and does not include the space above the categories. seems like a bug to me. let me have a look.
> 
> When adding the categories to the page, the hero gets the class of `column-page-left` like the content of the page but this should remain `column-page`. To me this seems like a bug. I am not sure how to bypass this.

Could also be a decision they made because the `main content` is on the left side. But for me the categories is also content otherwise you would not provide it.

**Comment by rcannood** [comment]
Apart from the tables sometimes looking a little wonky, this PR looks good to me. Should we merge it together with the results PR when we have a complete set of results?

**Comment by KaiWaldrant** [comment]
`break-word` not really working and all other solutions are a bit too "code intensive".

**Comment by KaiWaldrant** [comment]
The `kableExtra` only works on `latex` or `html` format. Setting the column widths isn't working atm. resting it for now.

**Review by rcannood — APPROVED** [review]

**Pull request merged**
